### ISSUE TITLE
Fehlermeldung bei Installation 

### ISSUE THREAD

**Issue by madiko** [TobiasKrais/d2u_machinery#1]
Hallo Tobias,

setzte heute eine lokale Instanz für REX auf und lud mir unter anderem auch Dein AddOn "d2u_machinery". Bei der Installation von "machine_steel_processing_extension" warf es mir folgende Fehlermeldung und die Installation wurde nicht ausgeführt. 

Ich geb Dir das mal weiter in der Hoffnung, dass Du damit was anfangen kannst. Noch ist es nicht akut, wäre aber schon schön, wenn ich es mir anschauen und testen kann.

Weil ich nur sehr wenig an den Fehlern verstehe, hier noch die Info: Für die DB stellte ich utf8_unicode_ci ein. Da unten ständig von utf8mb4 die Rede ist - ist das die Ursache?

Besten Dank und viele Grüße,
Franziska

> PlugIn machine_steel_processing_extension konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "ALTER TABLE rex_d2u_machinery_machines ADD process_ids VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER operating_voltage_a, ADD procedure_ids VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER process_ids, ADD material_ids VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER procedure_ids, ADD tool_ids VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER material_ids, ADD automation_supply_single_stroke VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER tool_ids, ADD automation_supply_multi_stroke VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER automation_supply_single_stroke, ADD automation_feedrate VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER automation_supply_multi_stroke, ADD automation_rush_leader_flyback VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER automation_feedrate, ADD automation_automationgrade_ids VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER automation_rush_leader_flyback, ADD automation_supply_ids VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER automation_automationgrade_ids, ADD workspace VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER automation_supply_ids, ADD workspace_square VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER workspace, ADD workspace_flat VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER workspace_square, ADD workspace_plate VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER workspace_flat, ADD workspace_profile VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER workspace_plate, ADD workspace_angle_steel VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER workspace_profile, ADD workspace_round VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER workspace_angle_steel, ADD workspace_min VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER workspace_round, ADD sheet_width VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER workspace_min, ADD sheet_length VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER sheet_width, ADD sheet_thickness VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER sheet_length, ADD tool_changer_locations VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER sheet_thickness, ADD drilling_unit_vertical VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER tool_changer_locations, ADD drilling_unit_horizontal VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER drilling_unit_vertical, ADD drilling_diameter VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER drilling_unit_horizontal, ADD drilling_tools_axis VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER drilling_diameter, ADD drilling_axis_drive_power VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER drilling_tools_axis, ADD drilling_rpm_speed VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER drilling_axis_drive_power, ADD saw_blade VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER drilling_rpm_speed, ADD saw_band VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER saw_blade, ADD saw_band_tilt VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER saw_band, ADD saw_cutting_speed VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER saw_band_tilt, ADD saw_miter VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER saw_cutting_speed, ADD bevel_angle int(10) DEFAULT NULL AFTER saw_miter, ADD punching_diameter VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER bevel_angle, ADD punching_power INT(5) NULL DEFAULT NULL AFTER punching_diameter, ADD punching_tools VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER punching_power, ADD shaving_unit_angle_steel_single_cut int(10) DEFAULT NULL AFTER punching_tools, ADD profile_ids VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER shaving_unit_angle_steel_single_cut, ADD carrier_width VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER profile_ids, ADD carrier_height VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER carrier_width, ADD carrier_weight int(10) DEFAULT NULL AFTER carrier_height, ADD flange_thickness VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER carrier_weight, ADD web_thickness VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER flange_thickness, ADD component_length VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER web_thickness, ADD component_weight int(10) DEFAULT NULL AFTER component_length, ADD welding_process_ids VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER component_weight, ADD welding_thickness int(10) DEFAULT NULL AFTER welding_process_ids, ADD welding_wire_thickness VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER welding_thickness, ADD beam_continuous_opening VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER welding_wire_thickness, ADD beam_turbines int(3) DEFAULT NULL AFTER beam_continuous_opening, ADD beam_turbine_power VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER beam_turbines, ADD beam_color_guns VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER beam_turbine_power"! SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

**Comment by TobiasKrais** [comment]
Danke für die Fehlermeldung. Kannst du bitte folgendes probieren: bitte deinstalliere und lösche das komplette Addon. Ziehe dir dann die aktuelle Git Version und installiere diese. Kommt der Fehler immernoch?

Hintergrund: auf deinem Server ist der Speicher für die Spalten mit VARCHAR strenger limitiert als auf meinem Server. Deshalb kam der Fehler bei mir noch nicht.

**Comment by madiko** [comment]
Hm, scheint auch nicht zu wollen. Bevor ich das AddOn deinstallieren kann, werde ich ja aufgefordert, "export" zu deinstallieren. 

Dabei erhalte ich jedoch diese Fehlermeldung:

> PlugIn export konnte aus folgendem Grund nicht deinstalliert werden:
SQL error: Error while executing statement "ALTER TABLE rex_d2u_machinery_categories DROP export_machinerypark_category_id, DROP export_europemachinery_category_id, DROP export_europemachinery_category_name, DROP export_mascus_category_name;"! SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP COLUMN `export_machinerypark_category_id`; check that it exists

Ein deaktivieren ist möglich - jedoch keine Deinstallation.

**Comment by TobiasKrais** [comment]
OK. Danke! Im Export Plugin habe ich jetzt die install.php und uninstall.php angepasst. Bitte lade die beiden Dateien auch nochmals von Git runter und reinstalliere das Plugin. Dann sollte das deinstallieren auch klappen.

**Comment by madiko** [comment]
Hallo Tobias,

lud mir alle heute geänderten install.php runter und führte ein reinstall durch. 

Bei "export" scheinst Du noch nicht synchronisiert zu haben?
https://github.com/TobiasKrais/d2u_machinery/tree/master/plugins/export

PlugIn machine_steel_processing_extension wirft denselben Fehler wie oben.

Danke, dass Du Dich so schnell darum kümmerst. Das hatte ich gar nicht erwartet.

Viele Grüße,
Franziska

**Comment by TobiasKrais** [comment]
Oh, stimmt. Die Änderungen im Export sind nicht übertragen worden. Jetzt klappt es.

Ein reinstall der ganzen Plugins reicht nicht. Du müsstest es komplett deinstallieren und neu installieren.

**Comment by madiko** [comment]
Du verweist leider in der deinstall.php auf eine Datei, die es im repository nicht gibt:

 ErrorException (E_COMPILE_ERROR)
require_once() : Failed opening required 'lib/export_backend_helper.php' (include_path='C:\xampp\php\PEAR')

[edit] Zeile 17 + 18 im code. Pardon, das hab ich vergessen, dazuzuschreiben.

**Comment by TobiasKrais** [comment]
Oh, oh! Da merkst du wie oft ich das in letzter Zeit deinstalliert habe... Sorry. Der Fehler ist jetzt auch behoben.

**Comment by madiko** [comment]
Yeah! export ließ sich jetzt deinstallieren.

Ich trau es mich kaum zu schreiben, bei machine_construction_equipment_extension gibt es jedoch noch eine Fehlermeldung (bei deinstall)

> PlugIn machine_construction_equipment_extension konnte aus folgendem Grund nicht deinstalliert werden:
SQL error: Error while executing statement "ALTER TABLE rex_d2u_machinery_machines DROP airless_hose_connection, DROP airless_hose_diameter, DROP airless_hose_length, DROP airless_nozzle_size, DROP container_capacity, DROP container_mixing_performance, DROP container_waterconnect_pressure, DROP container_waterconnect_diameter, DROP container_weight_empty, DROP cutters_cutting_depth, DROP cutters_cutting_length, DROP cutters_rod_length, DROP floor_beam_power_on_concrete, DROP floor_dust_extraction_connection, DROP floor_feedrate, DROP floor_filter_connection, DROP floor_rotations, DROP floor_working_pressure, DROP floor_working_width, DROP grinder_grinding_plate, DROP grinder_grinding_wheel, DROP grinder_rotational_frequency, DROP grinder_sanding, DROP grinder_vacuum_connection, DROP operating_pressure, DROP picture_delivery_set, DROP pump_conveying_distance_fluid, DROP pump_conveying_distance_mineral, DROP pump_conveying_distance_pasty, DROP pump_filling, DROP pump_flow_volume_fluid, DROP pump_flow_volume_mineral, DROP pump_flow_volume_pasty, DROP pump_grain_size, DROP pump_material_container, DROP pump_pressure_height_fluid, DROP pump_pressure_height_mineral, DROP pump_pressure_height_pasty, DROP waste_water_capacity;"! SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP COLUMN `picture_delivery_set`; check that it exists

**Comment by TobiasKrais** [comment]
OK. Jetzt habe ich mal alle Plugins umgestellt. Bitte probiers mit der aktuellen Git Version...

**Comment by TobiasKrais** [comment]
Fehler sollte in 1.3.1 behoben sein.
