### ISSUE TITLE
1.4.0 update error: Access level ... must be public

### ISSUE THREAD

**Issue by staabm** [TobiasKrais/d2u_machinery#2]
1.4.0 lässt sich nicht auf 1.4.1 updaten wg. folgendem fehler (whoops).
der fehler erscheint be durchführen des updates und auch beim deinstallieren von 1.4.0

**ErrorException:** Access level to d2u_machinery_lang_helper::$replacements_english must be public (as in class D2U_Helper\ALangHelper)
**File:** redaxo/src/addons/d2u_machinery/lib/d2u_machinery_lang_helper.php
**Line:** 5

<details>
<summary>Stacktrace</summary>

| Function                    | File     | Line     |
| --------------------------- | -------- | -------- |
| rex_error_handler::shutdown |          |          |

</details>
<details>
<summary>System report (REDAXO 5.15.1#8907a3a4c, PHP 8.1.17, MariaDB 10.11.2)</summary>

| REDAXO        |                  |
| ------------: | :--------------- |
|       Version | 5.15.1#8907a3a4c |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 8.1.17                         |
|       OPcache | no                             |
|        Xdebug | no                             |
|       Warning | Das Setup wird unverschlüsselt durchgeführt. Frontend und Backend sollten grundsätzlich durch HTTPS verschlüsselt aufgerufen werden, um die Privatsphäre zu schützen und den Datenschutz zu gewährleisten. |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.11.2 |
| Character set | utf8mb4         |

| Database 2    |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.11.2 |

| Database 3    |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.11.2 |

| Server        |                |
| ------------: | :------------- |
|            OS | Darwin         |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.56  |

| Request       |               |
| ------------: | :------------ |
|       Browser | Firefox/113.0 |
|      Protocol | HTTP/1.1      |
|         HTTPS | no            |

| Packages          |            |
| ----------------: | :--------- |
|           adminer | 1.9.3      |
|            backup | 2.9.0      |
|          be_style | 3.2.0      |
|   be_style/redaxo | 3.2.0      |
|        d2u_helper | 1.10.1     |
|         developer | 3.9.2      |
|           install | 2.11.1     |
|          markitup | 3.7.4      |
|     media_manager | 2.14.0     |
|         mediapool | 2.13.0     |
|          metainfo | 2.10.0     |
|           project | dev        |
|         rexfactor | 0.1.1      |
|           rexstan | 1.0.106    |
|    rexstansqltest | 0.0.0      |
|             sprog | 1.5.1      |
|         structure | 2.15.0     |
| structure/content | 2.15.0     |
|               url | 2.1.0      |
|             users | 2.10.0     |
|            watson | 2.3.0      |
|             yform | 4.1.0      |
|       yform/email | 4.1.0      |
|     yform/manager | 4.1.0      |
|          yrewrite | 2.9.1      |

</details>

**Comment by TobiasKrais** [comment]
Ja, ist mir leider bekannt. Um das Update auszuführen musst du vorher das d2u_macheriny Addon deaktivieren. Dann das Update und dann wieder aktivieren.

Das Dumme ist, dass das Addon eine Klasse aus d2u_helper erbt. Für die Variable `$replacements_english` ist die Sichtbarkeit `protected` ausreichend. Diese Sichtbarkeit kann ich aber nicht einführen, da ich nicht beide Addons gleichzeitig aktualisieren kann. Das war mir aber nicht bewusst...
